require 'test_helper'

describe RightClickAttrs do
  describe "#call" do
    describe "with user passed" do
      before do
        @user = FactoryGirl.create(:user, uid: "123", model_names: ["Invoice__c", "Merchandise__c", "Line_Item__c"])
        @invoice = @user.invoices.create( otype: "Invoice__c", data: { "Id"=>"a00i000000BbWLvAAN", "OwnerId"=>"005i0000002NdyWAAS", "Owner"=>nil, "IsDeleted"=>false, "Name"=>"INV-0000", "CreatedDate"=>"2013-11-25T00:26:05+00:00", "CreatedById"=>"005i0000002NdyWAAS", "CreatedBy"=>nil, "LastModifiedDate"=>"2014-01-28T06:16:41+00:00", "LastModifiedById"=>"005i0000002NdyWAAS", "LastModifiedBy"=>nil, "SystemModstamp"=>"2014-01-28T06:16:41+00:00", "Status__c"=>"Closed", "Invoice_Total__c"=>999.0, "PDF_Link__c"=>"https://localhost:3001/invoices/a00i000000BbWLvAAN" })
        @line_item = LineItem.create(  otype: "Line_Item__c", data: { "Id"=>"a01i0000007kDbrAAE", "IsDeleted"=>false, "Name"=>"i", "CreatedDate"=>"2013-11-25T00:26:05+00:00", "CreatedById"=>"005i0000002NdyWAAS", "CreatedBy"=>nil, "LastModifiedDate"=>"2013-12-03T06:46:58+00:00", "LastModifiedById"=>"005i0000002NdyWAAS", "LastModifiedBy"=>nil, "SystemModstamp"=>"2013-12-03T06:46:58+00:00", "Invoice__c"=>"a00i000000BbWLvAAN", "Invoice__r"=>nil, "Line_Item_Total__c"=>999.0, "Merchandise__c"=>"a02i00000096VuwAAE", "Merchandise__r"=>nil, "Quantity__c"=>1.0, "Unit_Price__c"=>999.0 })
        @merchandise = Merchandise.create(otype: "Merchandise__c", data: {"Id"=>"a02i00000096VuwAAE", "OwnerId"=>"005i0000002NdyWAAS", "Owner"=>nil, "IsDeleted"=>false, "Name"=>"Laptop", "CreatedDate"=>"2013-11-25T00:26:04+00:00", "CreatedById"=>"005i0000002NdyWAAS", "CreatedBy"=>nil, "LastModifiedDate"=>"2013-11-25T00:26:04+00:00", "LastModifiedById"=>"005i0000002NdyWAAS", "LastModifiedBy"=>nil, "SystemModstamp"=>"2013-11-25T00:26:04+00:00", "LastActivityDate"=>nil, "Price__c"=>500.0, "Quantity__c"=>1000.0 })
        PlyRelation.create(parent_id: @line_item.id, parent_type: "Line_Item__c", child_id: @invoice.id, child_type: "Invoice__c")
        PlyRelation.create(parent_id: @line_item.id, parent_type: "Line_Item__c", child_id: @merchandise.id, child_type: "Merchandise__c")
      end

      it "should return the sf_object instance" do
        RightClickAttrs.(@user.id, @invoice.id).must_equal "{\"invoice_fold\":{\"items\":{\"invoice_Id\":{\"name\":\"Id\"},\"invoice_OwnerId\":{\"name\":\"OwnerId\"},\"invoice_Owner\":{\"name\":\"Owner\"},\"invoice_IsDeleted\":{\"name\":\"IsDeleted\"},\"invoice_Name\":{\"name\":\"Name\"},\"invoice_CreatedDate\":{\"name\":\"CreatedDate\"},\"invoice_CreatedById\":{\"name\":\"CreatedById\"},\"invoice_CreatedBy\":{\"name\":\"CreatedBy\"},\"invoice_LastModifiedDate\":{\"name\":\"LastModifiedDate\"},\"invoice_LastModifiedById\":{\"name\":\"LastModifiedById\"},\"invoice_LastModifiedBy\":{\"name\":\"LastModifiedBy\"},\"invoice_SystemModstamp\":{\"name\":\"SystemModstamp\"},\"invoice_Status__c\":{\"name\":\"Status__c\"},\"invoice_Invoice_Total__c\":{\"name\":\"Invoice_Total__c\"},\"invoice_PDF_Link__c\":{\"name\":\"PDF_Link__c\"}},\"name\":\"Invoice__c\"},\"line_item_fold\":{\"items\":{\"line_item_Id\":{\"name\":\"Id\"},\"line_item_IsDeleted\":{\"name\":\"IsDeleted\"},\"line_item_Name\":{\"name\":\"Name\"},\"line_item_CreatedDate\":{\"name\":\"CreatedDate\"},\"line_item_CreatedById\":{\"name\":\"CreatedById\"},\"line_item_CreatedBy\":{\"name\":\"CreatedBy\"},\"line_item_LastModifiedDate\":{\"name\":\"LastModifiedDate\"},\"line_item_LastModifiedById\":{\"name\":\"LastModifiedById\"},\"line_item_LastModifiedBy\":{\"name\":\"LastModifiedBy\"},\"line_item_SystemModstamp\":{\"name\":\"SystemModstamp\"},\"line_item_Invoice__c\":{\"name\":\"Invoice__c\"},\"line_item_Invoice__r\":{\"name\":\"Invoice__r\"},\"line_item_Line_Item_Total__c\":{\"name\":\"Line_Item_Total__c\"},\"line_item_Merchandise__c\":{\"name\":\"Merchandise__c\"},\"line_item_Merchandise__r\":{\"name\":\"Merchandise__r\"},\"line_item_Quantity__c\":{\"name\":\"Quantity__c\"},\"line_item_Unit_Price__c\":{\"name\":\"Unit_Price__c\"}},\"name\":\"Line_Item__c\"},\"merchandise_fold\":{\"items\":{\"merchandise_Id\":{\"name\":\"Id\"},\"merchandise_OwnerId\":{\"name\":\"OwnerId\"},\"merchandise_Owner\":{\"name\":\"Owner\"},\"merchandise_IsDeleted\":{\"name\":\"IsDeleted\"},\"merchandise_Name\":{\"name\":\"Name\"},\"merchandise_CreatedDate\":{\"name\":\"CreatedDate\"},\"merchandise_CreatedById\":{\"name\":\"CreatedById\"},\"merchandise_CreatedBy\":{\"name\":\"CreatedBy\"},\"merchandise_LastModifiedDate\":{\"name\":\"LastModifiedDate\"},\"merchandise_LastModifiedById\":{\"name\":\"LastModifiedById\"},\"merchandise_LastModifiedBy\":{\"name\":\"LastModifiedBy\"},\"merchandise_SystemModstamp\":{\"name\":\"SystemModstamp\"},\"merchandise_LastActivityDate\":{\"name\":\"LastActivityDate\"},\"merchandise_Price__c\":{\"name\":\"Price__c\"},\"merchandise_Quantity__c\":{\"name\":\"Quantity__c\"}},\"name\":\"Merchandise__c\"}}"
      end
    end
  end
end
