require 'test_helper'

describe RightClickAttrs do
  describe "#call" do
    describe "with user passed" do
      before do
        @user = FactoryGirl.create(
          :user,
          uid: "123",
          invoice_api_name: "Invoice__c",
          line_item_api_name: "Line_Item__c",
          other_model_names: ["Merchandise__c"]
        )
        @invoice = @user.invoices.create( otype: "Invoice__c", data: { "Id"=>"a00i000000BbWLvAAN", "OwnerId"=>"005i0000002NdyWAAS", "Owner"=>nil, "IsDeleted"=>false, "Name"=>"INV-0000", "CreatedDate"=>"2013-11-25T00:26:05+00:00", "CreatedById"=>"005i0000002NdyWAAS", "CreatedBy"=>nil, "LastModifiedDate"=>"2014-01-28T06:16:41+00:00", "LastModifiedById"=>"005i0000002NdyWAAS", "LastModifiedBy"=>nil, "SystemModstamp"=>"2014-01-28T06:16:41+00:00", "Status__c"=>"Closed", "Invoice_Total__c"=>999.0, "PDF_Link__c"=>"https://localhost:3001/invoices/a00i000000BbWLvAAN" })
        @line_item = LineItem.create(  otype: "Line_Item__c", data: { "Id"=>"a01i0000007kDbrAAE", "IsDeleted"=>false, "Name"=>"i", "CreatedDate"=>"2013-11-25T00:26:05+00:00", "CreatedById"=>"005i0000002NdyWAAS", "CreatedBy"=>nil, "LastModifiedDate"=>"2013-12-03T06:46:58+00:00", "LastModifiedById"=>"005i0000002NdyWAAS", "LastModifiedBy"=>nil, "SystemModstamp"=>"2013-12-03T06:46:58+00:00", "Invoice__c"=>"a00i000000BbWLvAAN", "Invoice__r"=>nil, "Line_Item_Total__c"=>999.0, "Merchandise__c"=>"a02i00000096VuwAAE", "Merchandise__r"=>nil, "Quantity__c"=>1.0, "Unit_Price__c"=>999.0 })
        @merchandise = Merchandise.create(otype: "Merchandise__c", data: {"Id"=>"a02i00000096VuwAAE", "OwnerId"=>"005i0000002NdyWAAS", "Owner"=>nil, "IsDeleted"=>false, "Name"=>"Laptop", "CreatedDate"=>"2013-11-25T00:26:04+00:00", "CreatedById"=>"005i0000002NdyWAAS", "CreatedBy"=>nil, "LastModifiedDate"=>"2013-11-25T00:26:04+00:00", "LastModifiedById"=>"005i0000002NdyWAAS", "LastModifiedBy"=>nil, "SystemModstamp"=>"2013-11-25T00:26:04+00:00", "LastActivityDate"=>nil, "Price__c"=>500.0, "Quantity__c"=>1000.0 })
        PlyRelation.create(parent_id: @line_item.id, parent_type: "Line_Item__c", child_id: @invoice.id, child_type: "Invoice__c")
        PlyRelation.create(parent_id: @line_item.id, parent_type: "Line_Item__c", child_id: @merchandise.id, child_type: "Merchandise__c")
      end

      it "should return the sf_object instance" do
        RightClickAttrs.(@user.id, @invoice.id).must_equal "{\"invoice_fold\":{\"items\":{\"Invoice__c-Id\":{\"name\":\"Id\"},\"Invoice__c-OwnerId\":{\"name\":\"OwnerId\"},\"Invoice__c-Owner\":{\"name\":\"Owner\"},\"Invoice__c-IsDeleted\":{\"name\":\"IsDeleted\"},\"Invoice__c-Name\":{\"name\":\"Name\"},\"Invoice__c-CreatedDate\":{\"name\":\"CreatedDate\"},\"Invoice__c-CreatedById\":{\"name\":\"CreatedById\"},\"Invoice__c-CreatedBy\":{\"name\":\"CreatedBy\"},\"Invoice__c-LastModifiedDate\":{\"name\":\"LastModifiedDate\"},\"Invoice__c-LastModifiedById\":{\"name\":\"LastModifiedById\"},\"Invoice__c-LastModifiedBy\":{\"name\":\"LastModifiedBy\"},\"Invoice__c-SystemModstamp\":{\"name\":\"SystemModstamp\"},\"Invoice__c-Status__c\":{\"name\":\"Status__c\"},\"Invoice__c-Invoice_Total__c\":{\"name\":\"Invoice_Total__c\"},\"Invoice__c-PDF_Link__c\":{\"name\":\"PDF_Link__c\"}},\"name\":\"Invoice__c\"},\"line_item_fold\":{\"items\":{\"Line_Item__c-Id\":{\"name\":\"Id\"},\"Line_Item__c-IsDeleted\":{\"name\":\"IsDeleted\"},\"Line_Item__c-Name\":{\"name\":\"Name\"},\"Line_Item__c-CreatedDate\":{\"name\":\"CreatedDate\"},\"Line_Item__c-CreatedById\":{\"name\":\"CreatedById\"},\"Line_Item__c-CreatedBy\":{\"name\":\"CreatedBy\"},\"Line_Item__c-LastModifiedDate\":{\"name\":\"LastModifiedDate\"},\"Line_Item__c-LastModifiedById\":{\"name\":\"LastModifiedById\"},\"Line_Item__c-LastModifiedBy\":{\"name\":\"LastModifiedBy\"},\"Line_Item__c-SystemModstamp\":{\"name\":\"SystemModstamp\"},\"Line_Item__c-Invoice__c\":{\"name\":\"Invoice__c\"},\"Line_Item__c-Invoice__r\":{\"name\":\"Invoice__r\"},\"Line_Item__c-Line_Item_Total__c\":{\"name\":\"Line_Item_Total__c\"},\"Line_Item__c-Merchandise__c\":{\"name\":\"Merchandise__c\"},\"Line_Item__c-Merchandise__r\":{\"name\":\"Merchandise__r\"},\"Line_Item__c-Quantity__c\":{\"name\":\"Quantity__c\"},\"Line_Item__c-Unit_Price__c\":{\"name\":\"Unit_Price__c\"}},\"name\":\"Line_Item__c\"},\"merchandise_fold\":{\"items\":{\"Merchandise__c-Id\":{\"name\":\"Id\"},\"Merchandise__c-OwnerId\":{\"name\":\"OwnerId\"},\"Merchandise__c-Owner\":{\"name\":\"Owner\"},\"Merchandise__c-IsDeleted\":{\"name\":\"IsDeleted\"},\"Merchandise__c-Name\":{\"name\":\"Name\"},\"Merchandise__c-CreatedDate\":{\"name\":\"CreatedDate\"},\"Merchandise__c-CreatedById\":{\"name\":\"CreatedById\"},\"Merchandise__c-CreatedBy\":{\"name\":\"CreatedBy\"},\"Merchandise__c-LastModifiedDate\":{\"name\":\"LastModifiedDate\"},\"Merchandise__c-LastModifiedById\":{\"name\":\"LastModifiedById\"},\"Merchandise__c-LastModifiedBy\":{\"name\":\"LastModifiedBy\"},\"Merchandise__c-SystemModstamp\":{\"name\":\"SystemModstamp\"},\"Merchandise__c-LastActivityDate\":{\"name\":\"LastActivityDate\"},\"Merchandise__c-Price__c\":{\"name\":\"Price__c\"},\"Merchandise__c-Quantity__c\":{\"name\":\"Quantity__c\"}},\"name\":\"Merchandise__c\"}}"
      end
    end
  end
end
