ROLES: [admin, user, VIP]

DATABASEDOTCOM_HOST: login.salesforce.com
DATABASEDOTCOM_DEBUGGING: true

production:
  DATABASEDOTCOM_CLIENT_SECRET: 2723513671397209288
  DATABASEDOTCOM_CLIENT_ID: 3MVG9A2kN3Bn17hvFwA0jJYrgAYRETsvZq0QNgJbEzijoUylgdu2vK6EoULwkkRgStSGHjHiQ0NZAGDgCiM7Z

development:
  DATABASEDOTCOM_CLIENT_SECRET: 826682111161954853
  DATABASEDOTCOM_CLIENT_ID: 3MVG9A2kN3Bn17hvugFcYc0B.vGBBRSd7xw7_xDwrml5zry8S9rteLT_vsWQf3XA2jcznwwpzh5WBr1bN5WMP
