ROLES: [admin, user, VIP]
DATABASEDOTCOM_HOST: login.salesforce.com
DATABASEDOTCOM_CLIENT_SECRET: 2723513671397209288
DATABASEDOTCOM_CLIENT_ID: 3MVG9A2kN3Bn17hvFwA0jJYrgAYRETsvZq0QNgJbEzijoUylgdu2vK6EoULwkkRgStSGHjHiQ0NZAGDgCiM7Z
DATABASEDOTCOM_DEBUGGING: true

