development: &nonproduction
  client_id: "3MVG9A2kN3Bn17hvFwA0jJYrgAYRETsvZq0QNgJbEzijoUylgdu2vK6EoULwkkRgStSGHjHiQ0NZAGDgCiM7Z"
  sobject_module: "SF"
  host: "login.salesforce.com"
  client_secret: "2723513671397209288"
  username: "mfpiccolo@gmail.com"
  password: "sac93!ronlMtOX4GbBiNSSLvOdI3PGdsur"
  debugging: "true"

test:
  <<: *nonproduction

staging:
  <<: *nonproduction

production:
  client_id: "3MVG9A2kN3Bn17hvFwA0jJYrgAYRETsvZq0QNgJbEzijoUylgdu2vK6EoULwkkRgStSGHjHiQ0NZAGDgCiM7Z"
  sobject_module: "SF"
  host: "login.salesforce.com"
  client_secret: "2723513671397209288"
  username: "mfpiccolo@gmail.com"
  password: "sac93!ronlMtOX4GbBiNSSLvOdI3PGdsur"
  debugging: "true"
