development: &dev
  adapter: postgresql
  encoding: unicode
  database: ready_invoice_development
  pool: 5
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  min_messages: warning
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ready_invoice_test
  pool: 5
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  min_messages: error
  host: localhost

production:
  <<: *dev
