---
client_id: 3MVG9A2kN3Bn17hvFwA0jJYrgAYRETsvZq0QNgJbEzijoUylgdu2vK6EoULwkkRgStSGHjHiQ0NZAGDgCiM7Z
host: login.salesforce.com
client_secret: 2723513671397209288
username: mfpiccolo@gmail.com
password: sac93!ron
debugging: true
